### ISSUE TITLE
Following ZenDesk README.md instructions results in file not found error

### ISSUE THREAD

**Issue by howdandy** [DeskPRO/deskpro-importer-tools#23]
I follow [https://github.com/DeskPRO/deskpro-importer-tools/blob/master/importers/zendesk/README.md](url)

after `php bin/import zendesk` I get the following:

> [E_WARNING:2] require_once(vendor/autoload.php): failed to open stream: No such file or directory (/usr/share/nginx/html/deskpro/bin/deskpro-importer-tools-master/importers/zendesk/lib/autoload.php:3)

> Fatal error: require_once(): Failed opening required 'vendor/autoload.php' (include_path='/usr/share/nginx/html/deskpro/app/19299/vendor-src/zend/library:/usr/share/nginx/html/deskpro/app/19299/vendor-src/ezcomponents:/usr/share/nginx/html/deskpro/app/19299/vendor-src/pear/lib:.:/usr/share/php') in /usr/share/nginx/html/deskpro/bin/deskpro-importer-tools-master/importers/zendesk/lib/autoload.php on line 3

> [UNKNOWN:64:64] require_once(): Failed opening required 'vendor/autoload.php' (include_path='/app/vendor-src/zend/library:/app/vendor-src/ezcomponents:/app/vendor-src/pear/lib:.:/usr/share/php') (/usr/share/nginx/html/deskpro/bin/deskpro-importer-tools-master/importers/zendesk/lib/autoload.php:3)

Am I missing something?

**Comment by syastrebov** [comment]
hey @howdandy , fixed the problem, please re-download the repo and try again.

**Comment by howdandy** [comment]
expected classes load and files are found now.  the import script executes.  Now every request results in a 401 Unauthorized.  

My credentials are correct: they work in a curl request.  

A var_dump of auth object in setAuth in ./importers/zendesk/lib/vendor/zendesk/lib/vendor/zendesk_api_client_php/src/Zendesk/API/HttpClient.php show that values are being correctly set from my config.php.

However, a var_dump of the Request class in the doApiRequest function in ./importers/zendesk/lib/src/ZenDesk/Request/RequestClientAdapter.php  shows that auth credentials aren't being passed.  

Should I open another ticket and collect some more info?
