### ISSUE TITLE
Zendesk importer response 401 Unauthorized

### ISSUE THREAD

**Issue by howdandy** [DeskPRO/deskpro-importer-tools#24]
My config.php is correctly set with my user@name/token username, my `domain` and an api token.  
A curl request to `https://domain.zendesk.com/api/v2/organization_fields.json` using the same credentials gives a 200 OK response.  

However, when I run `php /usr/share/nginx/html/deskpro/bin/import -vvv zendesk` I get:

`[2016-12-16 02:14:16] importer.INFO:
[2016-12-16 02:14:16] importer.INFO: Export `Organization custom definitions` section.
[2016-12-16 02:14:16] importer.INFO: =====================================
[2016-12-16 02:14:16] importer.INFO:

  [RuntimeException]
  Unable to connect, check ZenDesk exporter credentials

Exception trace:
 () at /usr/share/nginx/html/deskpro/bin/deskpro-importer-tools-master/importers/zendesk/lib/src/ZenDesk/Request/RequestClientAdapter.php:121
 DeskPRO\ImporterTools\Importers\ZenDesk\Request\RequestClientAdapter->doApiRequest() at /usr/share/nginx/html/deskpro/bin/deskpro-importer-tools-master/importers/zendesk/lib/src/ZenDesk/Request/RequestClientAdapter.php:82
 DeskPRO\ImporterTools\Importers\ZenDesk\Request\RequestClientAdapter->doRequest() at /usr/share/nginx/html/deskpro/bin/deskpro-importer-tools-master/importers/zendesk/lib/src/ZenDesk/Request/RequestCacheAdapter.php:70
 DeskPRO\ImporterTools\Importers\ZenDesk\Request\RequestCacheAdapter->doRequest() at /usr/share/nginx/html/deskpro/bin/deskpro-importer-tools-master/importers/zendesk/lib/src/ZenDesk/ZenDeskReader.php:157
 DeskPRO\ImporterTools\Importers\ZenDesk\ZenDeskReader->getOrganizationFields() at /usr/share/nginx/html/deskpro/bin/deskpro-importer-tools-master/importers/zendesk/zendesk.php:56
 require_once() at /usr/share/nginx/html/deskpro/app/19299/src/Application/ImportBundle/Command/ImportCommand.php:102
 Application\ImportBundle\Command\ImportCommand->execute() at /usr/share/nginx/html/deskpro/app/19299/vendor/symfony/symfony/src/Symfony/Component/Console/Command/Command.php:259
 Symfony\Component\Console\Command\Command->run() at /usr/share/nginx/html/deskpro/app/19299/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:860
 Symfony\Component\Console\Application->doRunCommand() at /usr/share/nginx/html/deskpro/app/19299/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:192
 Symfony\Component\Console\Application->doRun() at /usr/share/nginx/html/deskpro/app/19299/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php:92
 Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at /usr/share/nginx/html/deskpro/app/19299/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:123
 Symfony\Component\Console\Application->run() at /usr/share/nginx/html/deskpro/app/19299/sys/Boot/Boot.php:284
 DpSys\Boot\Boot::bootCli() at /usr/share/nginx/html/deskpro/app/run/targets/console.php:32
 require() at /usr/share/nginx/html/deskpro/bin/import:20

  [Zendesk\API\Exceptions\ApiResponseException]
  Client error: `GET https://domain.zendesk.com/api/v2/organization_fields.json` resulted in a `401 Unauthorized` response:
  {"error":"Couldn't authenticate you"}
   [details] {"error":"Couldn't authenticate you"}

Exception trace:
 () at /usr/share/nginx/html/deskpro/bin/deskpro-importer-tools-master/importers/zendesk/lib/vendor/zendesk/zendesk_api_client_php/src/Zendesk/API/Http.php:89
 Zendesk\API\Http::send() at /usr/share/nginx/html/deskpro/bin/deskpro-importer-tools-master/importers/zendesk/lib/vendor/zendesk/zendesk_api_client_php/src/Zendesk/API/HttpClient.php:395
 Zendesk\API\HttpClient->get() at /usr/share/nginx/html/deskpro/bin/deskpro-importer-tools-master/importers/zendesk/lib/vendor/zendesk/zendesk_api_client_php/src/Zendesk/API/Traits/Resource/FindAll.php:31
 Zendesk\API\Resources\Core\OrganizationFields->findAll() at /usr/share/nginx/html/deskpro/bin/deskpro-importer-tools-master/importers/zendesk/lib/src/ZenDesk/Request/ClientHelper/CoreAPI/OrganizationField.php:47
 DeskPRO\ImporterTools\Importers\ZenDesk\Request\ClientHelper\CoreAPI\OrganizationField->findAll() at /usr/share/nginx/html/deskpro/bin/deskpro-importer-tools-master/importers/zendesk/lib/src/ZenDesk/Request/RequestClientAdapter.php:103
 DeskPRO\ImporterTools\Importers\ZenDesk\Request\RequestClientAdapter->doApiRequest() at /usr/share/nginx/html/deskpro/bin/deskpro-importer-tools-master/importers/zendesk/lib/src/ZenDesk/Request/RequestClientAdapter.php:82
 DeskPRO\ImporterTools\Importers\ZenDesk\Request\RequestClientAdapter->doRequest() at /usr/share/nginx/html/deskpro/bin/deskpro-importer-tools-master/importers/zendesk/lib/src/ZenDesk/Request/RequestCacheAdapter.php:70
 DeskPRO\ImporterTools\Importers\ZenDesk\Request\RequestCacheAdapter->doRequest() at /usr/share/nginx/html/deskpro/bin/deskpro-importer-tools-master/importers/zendesk/lib/src/ZenDesk/ZenDeskReader.php:157
 DeskPRO\ImporterTools\Importers\ZenDesk\ZenDeskReader->getOrganizationFields() at /usr/share/nginx/html/deskpro/bin/deskpro-importer-tools-master/importers/zendesk/zendesk.php:56
 require_once() at /usr/share/nginx/html/deskpro/app/19299/src/Application/ImportBundle/Command/ImportCommand.php:102
 Application\ImportBundle\Command\ImportCommand->execute() at /usr/share/nginx/html/deskpro/app/19299/vendor/symfony/symfony/src/Symfony/Component/Console/Command/Command.php:259
 Symfony\Component\Console\Command\Command->run() at /usr/share/nginx/html/deskpro/app/19299/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:860
 Symfony\Component\Console\Application->doRunCommand() at /usr/share/nginx/html/deskpro/app/19299/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:192
 Symfony\Component\Console\Application->doRun() at /usr/share/nginx/html/deskpro/app/19299/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php:92
 Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at /usr/share/nginx/html/deskpro/app/19299/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:123
 Symfony\Component\Console\Application->run() at /usr/share/nginx/html/deskpro/app/19299/sys/Boot/Boot.php:284
 DpSys\Boot\Boot::bootCli() at /usr/share/nginx/html/deskpro/app/run/targets/console.php:32
 require() at /usr/share/nginx/html/deskpro/bin/import:20`

**Comment by syastrebov** [comment]
@howdandy created a test account `https://dptestsupport.zendesk.com/` to check credentials:

```
$CONFIG['account'] = [
    'subdomain' => 'dptestsupport',
    'username'  => 'pac1rax@dispostable.com',
    'token'     => 'U4LymUCnssSNGEcXEUMrLpQYLYqWYxnrAn5XU0aB',
    'auth_type' => 'basic',
];
```

please check if it works, guess problem with username, should be just email address not `user@name/token`.

**Comment by howdandy** [comment]
removing /token from the username worked.  a little different from instructions for API token auth at [https://developer.zendesk.com/rest_api/docs/core/introduction#security-and-authentication](https://developer.zendesk.com/rest_api/docs/core/introduction#security-and-authentication) but importer works as expected now.
